spring:
    datasource:
        url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
        driver-class-name: org.h2.Driver
        username: ${DATASOURCE_USERNAME:username}
        password: ${DATASOURCE_PASSWORD:password}

    h2:
        console:
            enabled: true
            path: /h2-console


    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

server:
    port: 8080

jwt:
    secret: ${JWT_SECRET:jwt_secret_key}
    expiration: 3600000   # 1 hour
    issuer: "urbanhomes-app"

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,loggers,env
    endpoint:s:
        health:
            show-details: always